# Generated by Django 4.0.5 on 2022-07-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primera_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automoviles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('anoxx', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Longevidad_animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=40)),
                ('longevidad', models.IntegerField()),
            ],
        ),
    ]
